[package]
name = "tmuxcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"

[dependencies.markdown-parser]
version = "*"
features = ["adapt"]